name: Upload Language Files 🌐
on:
  push:
    branches:
      - master
    paths:
      - "**/en-US.ini"
jobs:
  upload-language-files:
    name: Upload Language Files 🌐
    if: github.repository_owner == 'obsproject'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 100
      - name: Upload US English Language Files 🇺🇸
        uses: obsproject/obs-crowdin-sync/upload@4b488c7ced03aa109d9f12529bd91c26c54b3e89
        env:
          CROWDIN_PAT: ${{ secrets.CROWDIN_SYNC_CROWDIN_PAT }}
          GITHUB_EVENT_BEFORE: ${{ github.event.before }}
          SUBMODULE_NAME: obs-websocket
